### ISSUE TITLE
AttributeError: 'BC' object has no attribute 'num_of_params'

### ISSUE THREAD

**Issue by Loerbri** [eghouti/BinaryConnect#1]
Hi, thanks for the code.

I think the title is quite self explanatory. The attribute 'num_of_parameters' only appears in the clip function of the BC-class. Hence I get a syntax error when trying to run the training script.

**Comment by eghouti** [comment]
Hello, Thank you for your comment. Actually, there was an error in the code that I just fixed it. You can check now.

**Comment by Loerbri** [comment]
Thank you very much. Everything is working well now!
