### ISSUE TITLE
Loss criterion

### ISSUE THREAD

**Issue by pmirallesr** [eghouti/BinaryConnect#5]
Hello there,

I see that your code uses the CrossEntropy loss for BC, whereas their original paper used instead an L2-SVM with a squared hinge loss. When trying to do my own replica, I fail to obtain their performance by using the squared hinge loss, but manage just fine with CE. My question is: Have you tried to replicate their results using an L2SVM, and if so, did you succeed?

Thanks!

**Comment by eghouti** [comment]
Hello,
No I did not try
